[build]
  command = "composer install && npm run build && php artisan migrate --force"
  publish = "public"

[context.production.environment]
  PHP_VERSION = "8.2"
  PHP_INI_SCAN_DIR = "/opt/build/repo"